# Example YAMPA plugin artifact generated by OPAD.
RULE_ID = "example_traversal"
SERVICE = "notes"
PATTERN = "../"

def on_request(ctx, data):
    text = data.decode(errors="replace") if hasattr(data, "decode") else str(data)
    if PATTERN in text:
        ctx.log(f"OPAD_RULE_HIT {RULE_ID} service={SERVICE}")
        return b""
    return data

def on_response(ctx, data):
    return data
