from __future__ import annotations

import os
import re
import shlex
import subprocess
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any


@dataclass
class FilterRule:
    name: str
    service_name: str
    pattern: str
    pattern_type: str = "substring"  # substring | regex
    direction: str = "request"       # request | response | both
    action: str = "block"            # block | modify | log | slow
    provider: str = "ctf_proxy"      # ctf_proxy | yampa | nginx | iptables
    replacement: str | None = None
    enabled: bool = False


@dataclass
class ApplyGateResult:
    ok: bool
    checks: list[dict[str, Any]]
    warnings: list[str]


def _py_literal(s: str) -> str:
    return repr(s)


def ctf_proxy_filter(rule: FilterRule) -> str:
    """Generate a ctf_proxy Python filter draft.

    The exact ctf_proxy object names can vary by deployment; OPAD writes this as a
    human-reviewable filter body and keeps apply gated by checker replay.
    """
    match_expr = "False"
    target = "payload"
    if rule.pattern_type == "regex":
        match_expr = f"re.search({_py_literal(rule.pattern)}, {target}, re.I | re.S) is not None"
    else:
        match_expr = f"{_py_literal(rule.pattern)} in {target}"
    if rule.action == "block":
        action = "return False, b'OPAD_BLOCKED\\n'"
    elif rule.action == "modify":
        repl = rule.replacement or ""
        if rule.pattern_type == "regex":
            action = f"payload = re.sub({_py_literal(rule.pattern)}, {_py_literal(repl)}, payload.decode(errors='ignore')).encode(); return True, payload"
        else:
            action = f"return True, payload.replace({_py_literal(rule.pattern)}.encode(), {_py_literal(repl)}.encode())"
    elif rule.action == "slow":
        action = "time.sleep(1); return True, payload"
    else:
        action = "print('OPAD rule hit:', payload[:200]); return True, payload"
    return f'''# Generated by OPAD. Review before enabling in a real game.
# Service: {rule.service_name}
# Rule: {rule.name}
import re
import time


def filter_request(payload: bytes, ctx=None):
    text = payload.decode(errors="ignore")
    if {match_expr.replace(target, 'text')}:
        {action}
    return True, payload


def filter_response(payload: bytes, ctx=None):
    text = payload.decode(errors="ignore")
    return True, payload
'''


def yampa_plugin(rule: FilterRule) -> str:
    matcher = f"re.search({rule.pattern!r}, data, re.I | re.S)" if rule.pattern_type == "regex" else f"{rule.pattern!r} in data"
    if rule.action == "block":
        effect = "return b'OPAD_BLOCKED\\n'"
    elif rule.action == "modify":
        effect = f"return data.replace({rule.pattern!r}, {rule.replacement or ''!r})"
    else:
        effect = "print('OPAD YAMPA hit', data[:120]); return data"
    return f'''# Generated by OPAD for YAMPA plugin hooks.
# Put into a YAMPA plugin and enable only after checker replay passes.
import re


def filtering(data: bytes, flow):
    text = data.decode(errors="ignore")
    if {matcher.replace('data', 'text')}:
        {effect}
    return data
'''


def nginx_rule(rule: FilterRule, port: int | None = None) -> str:
    # Payload-aware blocking belongs in a proxy. NGINX draft is only for path/arg/header regexes.
    pat = rule.pattern.replace("'", "\\'")
    return f'''# OPAD draft for nginx. Prefer ctf_proxy/YAMPA for body-aware filters.
# service={rule.service_name} action={rule.action}
if ($request_uri ~* '{pat}') {{
    return 403;
}}
'''


def iptables_rule(rule: FilterRule, port: int | None = None) -> str:
    if rule.pattern_type not in {"ip", "cidr"}:
        return "# OPAD: iptables/nftables cannot safely match app payloads here; use ctf_proxy/YAMPA/NGINX."
    dest = f" --dport {int(port)}" if port else ""
    return f"iptables -A INPUT -p tcp{dest} -s {shlex.quote(rule.pattern)} -j DROP"


def render_rule(rule: FilterRule, service: dict[str, Any] | None = None) -> dict[str, Any]:
    port = int(service.get("port")) if service and service.get("port") else None
    if rule.provider == "ctf_proxy":
        body = ctf_proxy_filter(rule)
        path = f"filters/{rule.service_name}/{rule.name}.py"
    elif rule.provider == "yampa":
        body = yampa_plugin(rule)
        path = f"plugins/{rule.service_name}_{rule.name}.py"
    elif rule.provider == "nginx":
        body = nginx_rule(rule, port)
        path = f"nginx/opad_{rule.service_name}_{rule.name}.conf"
    elif rule.provider in {"iptables", "nftables"}:
        body = iptables_rule(rule, port)
        path = "shell/apply_filter.sh"
    else:
        body = "# Unsupported provider"
        path = "unsupported"
    return {"provider": rule.provider, "path": path, "content": body, "rule": asdict(rule)}


def simulate_rule(rule: FilterRule, samples: list[dict[str, Any]]) -> dict[str, Any]:
    hits = []
    rx = re.compile(rule.pattern, re.I | re.S) if rule.pattern_type == "regex" else None
    for i, sample in enumerate(samples):
        text = sample.get(rule.direction) or sample.get("request") or sample.get("data") or ""
        matched = bool(rx.search(text)) if rx else rule.pattern in text
        hits.append({"index": i, "label": sample.get("label"), "matched": matched, "expected": sample.get("expected")})
    return {"hits": hits, "matched": sum(1 for h in hits if h["matched"]), "total": len(hits)}


def gate_apply(rule: FilterRule, checker_samples: list[dict[str, Any]], suspicious_samples: list[dict[str, Any]], health_ok: bool = True) -> ApplyGateResult:
    checker = simulate_rule(rule, checker_samples)
    suspicious = simulate_rule(rule, suspicious_samples)
    warnings = []
    legit_blocked = checker["matched"] if rule.action == "block" else 0
    if legit_blocked:
        warnings.append(f"Rule would block {legit_blocked}/{checker['total']} checker-like samples")
    if suspicious["matched"] == 0:
        warnings.append("Rule does not match suspicious samples")
    if not health_ok:
        warnings.append("Service healthcheck is not OK")
    ok = health_ok and legit_blocked == 0 and suspicious["matched"] > 0
    checks = [
        {"name": "checker_replay", "ok": legit_blocked == 0, "detail": checker},
        {"name": "suspicious_replay", "ok": suspicious["matched"] > 0, "detail": suspicious},
        {"name": "healthcheck", "ok": health_ok, "detail": {}},
    ]
    return ApplyGateResult(ok=ok, checks=checks, warnings=warnings)


def dangerous_apply_enabled() -> bool:
    return os.getenv("OPAD_ENABLE_DANGEROUS_APPLY", "false").lower() in {"1", "true", "yes"}


def apply_rendered_rule(rendered: dict[str, Any], root: str | Path, confirm: bool = False) -> dict[str, Any]:
    if not confirm or not dangerous_apply_enabled():
        return {"ok": False, "dry_run": True, "reason": "Set confirm=true and OPAD_ENABLE_DANGEROUS_APPLY=true to write/apply rules", "rendered": rendered}
    root = Path(root)
    dest = root / rendered["path"]
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(rendered["content"], encoding="utf-8")
    return {"ok": True, "path": str(dest)}
